name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R system dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::remotes
            any::styler
            any::lintr
            any::testthat
            any::roxygen2

      - name: Lint code
        run: make lint

      - name: Run tests
        run: make test
